"""Public interface for deterministic hashing and provenance lineage."""

from .domains import HashDomain, HashRegion, validate_hash_domain
from .errors import (
    FileChangedError,
    FileSnapshotError,
    HashMismatchError,
    InvalidDigestError,
    InvalidHashDomainError,
    InvalidLineagePathError,
    InvalidProvenanceError,
    LineageCycleError,
    LineageError,
    ManifestValidationError,
    MissingParentError,
    UnsupportedLineageVersionError,
)
from .graph import LineageNode, validate_lineage_graph
from .hashing import (
    DEFAULT_CHUNK_SIZE,
    MAX_CHUNK_SIZE,
    sha256_bytes,
    sha256_file,
    snapshot_external_file,
    snapshot_local_file,
    validate_external_file,
    validate_local_file,
)
from .package import validate_package_members
from .values import (
    ConfigurationIdentity,
    FileIdentity,
    NamedIdentity,
    PathKind,
    ProvenanceRecord,
    SeedIdentity,
    Sha256Digest,
    build_provenance,
    provenance_items,
)

__all__ = (
    "DEFAULT_CHUNK_SIZE",
    "MAX_CHUNK_SIZE",
    "ConfigurationIdentity",
    "FileChangedError",
    "FileIdentity",
    "FileSnapshotError",
    "HashDomain",
    "HashMismatchError",
    "HashRegion",
    "InvalidDigestError",
    "InvalidHashDomainError",
    "InvalidLineagePathError",
    "InvalidProvenanceError",
    "LineageCycleError",
    "LineageError",
    "LineageNode",
    "ManifestValidationError",
    "MissingParentError",
    "NamedIdentity",
    "PathKind",
    "ProvenanceRecord",
    "SeedIdentity",
    "Sha256Digest",
    "UnsupportedLineageVersionError",
    "build_provenance",
    "provenance_items",
    "sha256_bytes",
    "sha256_file",
    "snapshot_external_file",
    "snapshot_local_file",
    "validate_external_file",
    "validate_hash_domain",
    "validate_lineage_graph",
    "validate_local_file",
    "validate_package_members",
)
