"""Canonical repository fixture paths shared by tests."""

from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
FIXTURES_ROOT = REPOSITORY_ROOT / "fixtures"
EXAMPLE_FIXTURES = FIXTURES_ROOT / "examples" / "pipeline"
TEST_FIXTURES = FIXTURES_ROOT / "tests"
PIPELINE_FIXTURE_ROOT = EXAMPLE_FIXTURES
DIAGNOSTIC_FIXTURE_ROOT = TEST_FIXTURES / "diagnostics"
DOCKER_FIXTURE_ROOT = TEST_FIXTURES / "docker"
PROCESS_GUARD_FIXTURE_ROOT = TEST_FIXTURES / "process_guard"
VALIDATION_STUDY_FIXTURE_ROOT = TEST_FIXTURES / "validation_study"
VALIDATION_STUDY_CANDIDATE = VALIDATION_STUDY_FIXTURE_ROOT / "candidate"
PRE_USER_AGENT_R6_FIXTURE = VALIDATION_STUDY_FIXTURE_ROOT / "pre-user-agent-r6"
