"""Direct unit tests for generated-artifact records and public validation."""

from __future__ import annotations

from dataclasses import FrozenInstanceError
from pathlib import Path
from typing import cast

import pytest

from trafficlab.artifacts.generated import GeneratedPublication, publish_generated_pcapng
from trafficlab.common.errors import TrafficlabError
from trafficlab.common.trace import CaptureMetadata, TrafficTrace


def test_generated_publication_retains_exact_fields_and_is_frozen(tmp_path: Path) -> None:
    """Published ownership evidence must retain exact values and reject later mutation."""
    path = tmp_path / "generated.pcapng"
    content = b"exact generated bytes"

    publication = GeneratedPublication(path, False, content)

    assert publication.path is path
    assert publication.created_by_call is False
    assert publication.content is content
    with pytest.raises(FrozenInstanceError):
        publication.created_by_call = True  # type: ignore[misc]


@pytest.mark.parametrize(
    ("expected_trace", "window", "exception", "match"),
    [
        (cast(TrafficTrace, ()), 1.0, TypeError, "TrafficTrace"),
        (TrafficTrace.from_events(()), True, TrafficlabError, "finite positive float"),
    ],
    ids=["trace-type", "window-type"],
)
def test_generated_publication_rejects_invalid_public_inputs_before_touching_filesystem(
    expected_trace: TrafficTrace,
    window: float,
    exception: type[BaseException],
    match: str,
) -> None:
    """Public validation must fail before resolving or opening the supplied run directory."""
    metadata = CaptureMetadata(interface="eth0", target_mac="02:42:ac:11:00:02")

    with pytest.raises(exception, match=match):
        publish_generated_pcapng(
            cast(Path, object()),
            b"not consulted",
            metadata=metadata,
            expected_trace=expected_trace,
            observation_window_seconds=window,
        )
